### ISSUE TITLE
spline_tentacle metarig End Twist Fix flipping UVs

### ISSUE THREAD

**Issue by StarshipAmelia** [angavrilov/angavrilov-rigs#10]
When twisting (along the local y axis) a mesh deformed with a spline_tentacle rig, at the point the rotation reaches around or above 180 degrees, the UV map for the model "flips" along the UV x axis. Changing the End Twist Fix value will change at what rotation this flipping occurs, but no value seems to fix it entirely.

I've also noticed that on exactly 180 degrees, some adjacent bones appear to be rotated 180 degrees relative to each other, resulting in an extreme twist in that mesh segment.

Is there a way to compensate for this either in the rig or in the texture? In animation it can result in flickering textures as the UV flips.

I'm using the [blender 2.93](https://github.com/angavrilov/angavrilov-rigs/releases/tag/blender-2.93) release on blender 2.93.

**Comment by angavrilov** [comment]
The whole reason there is an End Twist Fix slider is that it is impossible to find a value that would "fix it entirely", it has to be changed during the animation as needed. As stated in the readme:

> For technical reasons, the rig can only determine the chain twist from the tip control within the -180..180 degrees range. Exceeding that flips the twist direction. This option allows working around the limitation by dialing in a rough estimate of twist in full rotations, and letting the rig auto-correct to the precise value within the 180 degrees range from the estimate.

 Therefore this works like designed.
