### ISSUE TITLE
IK Spline Tentacle Regeneration Error

### ISSUE THREAD

**Issue by Kaitou-3D** [angavrilov/angavrilov-rigs#11]
[Raw Error Log](https://github.com/angavrilov/angavrilov-rigs/files/9079712/IK_Spline_Errorlog.txt)

Blender version: 3.2.0
a-rigs version : latest
Issue/Repro steps: Created a rig with IK SPline with default settings. Then went to add two more middle control points and regenerate control rig. Exception thrown by Rigify.
Current fix: Delete Rig-MCH spline objects first, then regenerate.

**Comment by angavrilov** [comment]
The rig was slightly modified and moved to the Rigify add-on itself. I couldn't reproduce this problem with that version.
