### ISSUE TITLE
Latest Master file doesn't work with Latest Build (Any Version Actually)

### ISSUE THREAD

**Issue by Layer29** [angavrilov/angavrilov-rigs#14]
I just downloaded the latest Master because I realized this was recently updated, and for some reason I can install the feature set in 

Rigify preferences, but they do not show up under Rigify Feature Set panel at all. I can add the advanced and regular Body Ik rigs, but 

when I select bone in pose mode and go under the Rigify panel I get: "ERROR: type "body_ik.__" does not exist."

**Comment by Layer29** [comment]
Sorry, latest build is incompatible, I went back to 2.93 version, and it still works with 3.41.

**Comment by angavrilov** [comment]
Added a tag for the last version that works with 3.4

**Comment by Layer29** [comment]
Thank you so much Alexander, much appreciated. I love using your feature set rigs, and I was wondering if in particular 

elbow/knee pinning will be incorporated into the standard Rigify rig (or new Blender rig) in the future? Thanks again, kepp up the great work!
