### ISSUE TITLE
Regenerate fails when using "limbs.spline_tentacle"

### ISSUE THREAD

**Issue by juliocargnin** [angavrilov/angavrilov-rigs#17]
The curves created by the limbs.spline_tentacle prevent the operator Regenerate to succeed.
We found that manually deleting the curves solve the issue but this is not ideal. Would be great if you could fix that so the script can delete all the created curves before the regenerate happens or other solution you might have in mind. Thanks!

**Comment by angavrilov** [comment]
The rig was slightly modified and moved to the Rigify add-on itself. I couldn't reproduce this problem with that version.
