### ISSUE TITLE
All menu are empty on Blender 2.90

### ISSUE THREAD

**Issue by tony-yo** [angavrilov/angavrilov-rigs#2]
Good evening,
I wasn't able to make it work on 2.90 and 2.91. I've installed it following instructions, but all menu are empty. 
I've tried to install it manually in rigify folder but, even so, it didn't work.
What can I do?
Thanks.
![Blender 05_01_2021 13_56_55](https://user-images.githubusercontent.com/77008516/103654247-e8be2a00-4f65-11eb-8c3b-9bc0516524f1.png)
![Blender 05_01_2021 13_58_25](https://user-images.githubusercontent.com/77008516/103654261-ef4ca180-4f65-11eb-99d2-99eff483539d.png)
![Blender 05_01_2021 13_56_26](https://user-images.githubusercontent.com/77008516/103654290-f96ea000-4f65-11eb-82c2-9ac86ff912be.png)
![Blender Preferences 05_01_2021 13_55_34](https://user-images.githubusercontent.com/77008516/103654339-08555280-4f66-11eb-86df-c7178cb360ec.png)

**Comment by angavrilov** [comment]
Master often requires the master nightly build of Blender or even experimental builds. A couple of older versions now listed as tags (tagged purely based on date): https://github.com/angavrilov/angavrilov-rigs/tags
