### ISSUE TITLE
error relating to generation of limbs.spline_tenticle

### ISSUE THREAD

**Issue by iam-jos** [angavrilov/angavrilov-rigs#6]
**System Information**
Operating system: macOS-10.15.7-x86_64-i386-64bit 64 Bits
Graphics card: AMD Radeon Pro 5500M OpenGL Engine ATI Technologies Inc. 4.1 ATI-3.10.18

**Blender Version**
Broken: version: 2.93.3, branch: master, commit date: 2021-08-17 18:30, hash: `rB8b80d19f3641`
Worked: it hasn't :( I originally tested it on the 2.93.0 beta. 

**Addon Information**
Name: Rigify (0, 6, 3)
Author: Nathan Vegdahl, Lucio Rossi, Ivan Cappiello, Alexander Gavrilov.

I cannot code and do not understand anything about it (beyond making tumblr themes back in the day lol).

**Short description of error**

Generation has thrown an exception: create_gear_widget() got an unexpected keyword argument 'size'.

**Exact steps for others to reproduce the error**

Running the 'Experimental Rigs by Alexander Gavrilov - legacy version 2.91', on blender 2.93.3 (probably where the error stems from) - the latest version of the addon doesn't work at all.

When trying to generate the rig, I get the error above. The error is in relation to the Spline IK Tentacle (limbs.spline_tentacle). The simplest way to reproduce the error would be to create a single bone and delete it in edit mode. Then, add sample 'limbs.spline_tenticle', and generate rig. 
![Screenshot 2021-08-18 at 15 36 20 (2)](https://user-images.githubusercontent.com/89148063/129920402-37af85f7-2849-4b64-8e74-009e2b5b14f9.png)
![Screenshot 2021-08-18 at 15 41 22 (2)](https://user-images.githubusercontent.com/89148063/129920416-9e82f0cc-2ee2-4c56-ac60-993d82f336c8.png)

**Comment by angavrilov** [comment]
Added a tag for 2.93
